version: 0.2

env:
    variables:
        S3_BUCKET: "prem.traders.angular"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install -y npm@latest
        - npm install -g @angular/cli
        - rm package-lock.json
  pre_build:
    commands:
    - npm install
  build:
    commands:
        - echo Build started ..
        - ng build --prod
        - ls -l -F
  post_build:
    commands:
            # Clear S3 bucket..
            - aws s3 rm s3://prem.traders.angular --recursive
            - echo S3 bucket is cleared.
            - aws s3 cp dist/prem.traders.angular s3://prem.traders.angular --recursive
            - echo Build completed on `date`

artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
paths:
    - node_modules/